name: test

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "preview/**"
    paths-ignore:
      - .github/dependabot.yml
      - LICENSE
      - README.md
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  gv-via-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: gittools/actions/gitversion/setup@v1
        with:
          versionSpec: 5.x
    
      - uses: gittools/actions/gitversion/execute@v1
        with:
          useConfigFile: true
          additionalArguments: /nofetch

  gv-via-dotnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

  gv-via-container: #fails
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
  
      - run: |
          docker run -v "${{ github.workspace }}:/repo" gittools/gitversion /repo /nofetch > GitVersion.json
          cat GitVersion.json

  gv-via-container-debug: #fails with unknown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
  
      - run: |
          docker run --name gvtest -v "${{ github.workspace }}:/repo" gittools/gitversion /repo /nofetch
          docker logs gvtest

  gv-via-container-debug2: #gets further but still fails
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
  
      - run: |
          docker run --name gvtest --entrypoint "" -v "$(pwd):/repo" gittools/gitversion /bin/bash -c "git config --global --add safe.directory '*'; /tools/dotnet-gitversion /repo"
          docker logs gvtest
